name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-jar
        path: target/*.jar

   
    - name: Build Docker Image
      run: docker build -t snake-game .

    - name: Save Docker Image
      run: docker save snake-game > snake-game.tar

    - name: Upload Docker Image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: snake-game.tar

    # CREATE GITHUB RELEASE
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/*.jar
          snake-game.tar